#!/usr/bin/env node
t0 = Date.now();
// Call `PureOfScript.shebang :: Effect Unit`
// TODO: prefer latest
import("../output/PureOfScript/bundle.js" || "../output/PureOfScript/index.js").then(PureOfScript => {
  t1 = Date.now();
  console.log(t1 - t0);
  PureOfScript.shebang();
});
process.on("beforeExit", () => {
  t2 = Date.now();
  console.log(t2 - t0, t2 - t1);
});
